name: Print Variables

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  Test-Variables:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Printing variables
      run: env | sort

    - name: Using Variables
      run: |
        echo Print github.repository: ${{ github.repository }}
        echo Print GITHUB_REF_NAME: $GITHUB_REF_NAME
        echo Print github.event.repository.name: ${{ github.event.repository.name }}
        
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ github.event.repository.name }}:${{ GITHUB_REF_NAME }}

    - name: Print image name
      run: docker image ls
    
  
